# Generated by Django 4.0.6 on 2022-07-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcod',
            name='register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='register',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.otpcod'),
            preserve_default=False,
        ),
    ]
