# Generated by Django 4.0.6 on 2022-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcod_register_user_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcod',
            name='register',
        ),
    ]
