# Generated by Django 4.0.6 on 2022-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otpcod_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register',
        ),
    ]
