# Generated by Django 4.0.6 on 2022-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcod',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
