# Generated by Django 4.0.6 on 2022-07-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpcod_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.otpcod'),
        ),
    ]
