# Generated by Django 4.0.6 on 2022-07-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register',
        ),
    ]
