# Generated by Django 4.0.6 on 2022-07-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_otpcod_user_created_user_otp_cod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='create_otp',
        ),
    ]
