# Generated by Django 4.0.6 on 2022-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_created_user_create_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_cod',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
