# Generated by Django 4.0.6 on 2022-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_otp_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_cod',
            new_name='otp_code',
        ),
    ]
