# Generated by Django 4.0.6 on 2022-08-07 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_otp_cod_user_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbe', models.CharField(max_length=20, unique=True)),
                ('otp_code', models.PositiveSmallIntegerField()),
                ('create_otp', models.DateTimeField(auto_now=True)),
                ('count_send', models.IntegerField()),
                ('register', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.BooleanField(default=False)),
                ('vip_start_date', models.DateTimeField()),
                ('vip_end_date', models.DateTimeField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('level', models.CharField(default='user', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
