# Generated by Django 4.0.6 on 2022-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_code_order_orders_status_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='code_order',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
