# Generated by Django 4.0.6 on 2022-09-17 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_status_order_alter_itemorder_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_code',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
