# Generated by Django 4.0.6 on 2022-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_code_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='code_order',
            field=models.CharField(default='<function uuid4 at 0x7fb1a918a160>', max_length=64),
        ),
    ]
