# Generated by Django 4.0.6 on 2022-09-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_code_order'),
        ('orders', '0010_alter_orders_code_order'),
    ]

    operations = [
    ]
