# Generated by Django 4.0.6 on 2022-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20220917_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='t',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
