# Generated by Django 4.0.6 on 2022-09-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orders_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='t',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
