# Generated by Django 4.0.6 on 2022-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orders_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='code_order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
