# Generated by Django 4.0.6 on 2022-09-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orders_code_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='code_order',
        ),
    ]
