# Generated by Django 4.0.6 on 2022-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orders_code_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='t',
            new_name='code_order',
        ),
    ]
