# Generated by Django 4.0.6 on 2022-08-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_artical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryartical',
            name='sub_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryartical',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryartical'),
        ),
    ]
