# Generated by Django 4.0.6 on 2022-08-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categoryproduct_product_subcategoryproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryproduct',
            name='parent_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct'),
            preserve_default=False,
        ),
    ]
