# Generated by Django 4.0.6 on 2022-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subcategoryproduct_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_files',
            field=models.URLField(blank=True, null=True),
        ),
    ]
