# Generated by Django 4.0.6 on 2022-09-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_filesproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesproduct',
            name='file_product',
        ),
    ]
