# Generated by Django 4.0.6 on 2022-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_filesproduct_file_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesproduct',
            name='file_product',
            field=models.FileField(default=1, max_length=254, upload_to='files_products_tutorial/None/'),
            preserve_default=False,
        ),
    ]
