# Generated by Django 4.0.6 on 2022-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_filesproduct_file_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesproduct',
            name='file_product',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='files_products_tutorial/None/'),
        ),
    ]
