# Generated by Django 4.0.6 on 2022-09-16 13:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_filesproduct_file_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_files',
        ),
        migrations.AlterField(
            model_name='filesproduct',
            name='file_product',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=products.models.generate_filename),
        ),
    ]
