# Generated by Django 4.0.6 on 2022-09-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_answercomment_comment_alter_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
