# Generated by Django 4.0.6 on 2022-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_answercomment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to='comment.answercomment'),
        ),
    ]
